"""OD0-R48 adjudication data (Claude Code executor, package v0.2).

This module is pure data: the executor's theorem-first classifications,
genealogy arrows, GM/LG matrices, map classifications, maturation-field
inventory, CCE audit, hostile controls, and verdicts. It is consumed by
build_r48_outputs.py, which merges it deterministically with the raw census
(R48_CENSUS_GROUPS_RAW.json) to emit the required output files.

Every claim cites its exact source (file, section, or frozen-input artifact).
No historical numerical maturation content was parsed anywhere in this round.
"""

RUN_DATE = "2026-09-01"

# ---------------------------------------------------------------------------
# Frozen-input citations used throughout (path -> role)
# ---------------------------------------------------------------------------
CITES = {
    "CD0_SPEC": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/deu_combinatorial_descent_cd0/SPEC_CD0_DISTINCTION_CATEGORY_AND_COMPLEX_v0_1.md",
    "CD0_REPORT": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/deu_combinatorial_descent_cd0/CD0_DISTINCTION_EVENT_CATEGORY_REPORT.md",
    "CD0_TRIADIC_SCOUT": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/deu_combinatorial_descent_cd0/CD0_TRIADIC_REFINEMENT_SCOUT.md",
    "CD0_TRIADIC_DECISION": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/deu_combinatorial_descent_cd1_incidence/CD0_TRIADIC_FAILURE_DECISION_v0_1_1.md",
    "CD1I_FRAME": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/deu_combinatorial_descent_cd1_incidence/CD1I_INCIDENCE_FRAME_CLASSIFICATION.md",
    "CD1I_INVENTORY": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/deu_combinatorial_descent_cd1_incidence/CD1I_UEQ0_EQUIVALENCE_INVENTORY.md",
    "UEQ0_MASTER": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/UEQ0_MASTER_TRANSITION_THEOREM.md",
    "UEQ0_AXIOMS": "DEU_LER_v0_1_Codex_Package/deu_ler_v0_1/deu_unified_equations_v1_0/UEQ0_PROVENANCE_AND_AXIOM_LEDGER.md",
    "OD0_R0_SPEC": "DEU_LER_v2_codex/od0/OD0_SPEC_v0_1.md",
    "R33_SPEC": "DEU_LER_v2_codex/deu_od0_exact_observables_v0_1/od0_r33_policy_robust_sectors_v0_1/OD0_R33_SPEC_v0_1.md",
    "R32_SPEC": "DEU_LER_v2_codex/deu_od0_exact_observables_v0_1/od0_r32_fresh_record_controlled_cocycle_v0_1/OD0_R32_SPEC_v0_1.md",
    "R44_SPEC": "DEU_LER_v2_codex/deu_od0_exact_observables_v0_1/od0_r44_interval_cocycle_currents_v0_1/OD0_R44_SPEC_v0_1.md",
    "R47_REPORT": "DEU_LER_v2_codex/deu_od0_exact_observables_v0_1/od0_r47_geometry_no_carrier_boundary_v0_1/OD0_R47_REPORT.md",
    "R30_FROZEN": "package Section 3.1 frozen citation; artifact od0_r30_outer_policy_audit_v0_1 reachable through pinned chain (R48_CHAIN_VERIFICATION.json)",
    "LEDGER": "DEU_LER_v3_claude/MODEL_GENEALOGY.md",
    "PROVENANCE": "DEU_LER_v3_claude/MISSING_PROVENANCE.md",
    "CENSUS": "DEU_LER_v3_claude/R48_CENSUS_GROUPS_RAW.json",
}

# ---------------------------------------------------------------------------
# Adjudicated model families.
# member refs are (census_group, family_label_prefix) pairs into the raw census.
# Class overrides of census-agent proposals are recorded explicitly.
# ---------------------------------------------------------------------------
FAMILIES = [
    {
        "family_id": "F0_OD0_LOCAL",
        "name": "OD0 local event equation (frozen arbitrary-prestate controlled cocycle)",
        "final_class": "ACTIVE_OD0_LOCAL_EXACT",
        "summary": "Z=(x,N,S,Lambda,G-,G+); Pr(h,sigma|Z,gamma)=p_{gamma,h}(x)*K_svc(sigma|J_h,Lambda); triangular updates; x = 36-coordinate Q2 record frontier, N in N^2304 (P4 multiplicities), S subset 356-element persistent content alphabet (R33 Sec 1.1); Gamma_5184 full query-plus-setting controls in 13 covariance orbits (R32); G-(R)=Int(R), G+(R)=Cl(R) over RRP1 served marks (R44). Externally controlled; conditional premises PBO1/ERL1/RRP1 (+CCP1 for carrier chains, R47).",
        "members": [["G7_ler_v2_codex", "OD0 Q1 depth-1 exact successor kernel"],
                    ["G7_ler_v2_codex", "OD0 finite occurrence graph state"],
                    ["G8_ler_v01_and_misc", "LER0 lineage-embedding-render"],
                    ["G8_ler_v01_and_misc", "LERF frozen tower"],
                    ["G8_ler_v01_and_misc", "A13R scale-natural clock service"],
                    ["G8_ler_v01_and_misc", "BELL0/BELL1 canonical bipartite core"]],
        "overrides": [],
        "cites": ["OD0_R0_SPEC", "R33_SPEC", "R32_SPEC", "R44_SPEC", "R47_REPORT"],
    },
    {
        "family_id": "F1_NATIVE_CONSTRUCTOR",
        "name": "Native recursive distinction constructor and CD0 event/trace category",
        "final_class": "ACTIVE_NATIVE_DISTINCTION_CONSTRUCTOR",
        "summary": "Genesis {a,b}; objects = unordered pairs of distinct priors; universe O_<=7 (173 objects, 137 at level 7, sectors 81/40/16); states = ancestry-closed ideals containing {a,b}; transitions = adjunction events e_y enabled iff Par(y) subset X; exact independence diamonds (9,316 level-7 pairs verified); thin trace category (one arrow per comparable state pair); C2 primitive-exchange natural automorphism. NO opportunity/selection law: CD0 explicitly 'not asserted to be the runtime scheduler'; 'construction order cannot be a physical outcome or retained record'.",
        "members": [["G1_rmr_logical_seed", "Recursive DAG-7 registry constructor"],
                    ["G8_ler_v01_and_misc", "CD0 native recursive distinction constructor"],
                    ["G9_rmr_side_trees", "qdag packaged 137-registry toolkit"],
                    ["G9_rmr_side_trees", "de_pipeline canonical distinction-engine structural pipeline"]],
        "merge_certificate": "Merged on identical constructor rule read from code (unordered pair of distinct priors, ancestry closure) and identical exact universe (levels 1..7 = 2,0,1,2,6,25,137; CD0 report table), not on shared counts or names. The sterile-harness registry rebuild (G1) is a verifier copy, kept as AUDIT_ONLY member of family FA_STERILE.",
        "overrides": [],
        "cites": ["CD0_SPEC", "CD0_REPORT"],
    },
    {
        "family_id": "F1B_CD1I_DESCENT",
        "name": "CD1I incidence-odometer descent certificates (arrow artifact F1 -> LER representation core)",
        "final_class": "AUDIT_ONLY",
        "summary": "Certifies the typed incidence frame (IN=p, CO=q, NEW=x) as CANONICAL_FUNCTORIAL_SUBCONSTRUCTION and CDA1 as CANONICAL_DERIVED_REPRESENTATION with zero remaining representation axioms; derives qutrit, F3 character transform, frontier word space, refinement isometry, oriented shift, nested ternary clock, A9 fiber, A10 records, A11R Boolean facts. A12 and A13 explicitly out of scope; Hilbert substrate inherited from frozen UEQ0.",
        "members": [["G8_ler_v01_and_misc", "CD1I incidence odometer descent"]],
        "overrides": [["G8_ler_v01_and_misc", "CD1I incidence odometer descent",
                       "ACTIVE_OD0_LOCAL_EXACT", "AUDIT_ONLY",
                       "CD1I is a descent-certificate harness, not the local law family itself; its content is recorded as genealogy arrows."]],
        "cites": ["CD1I_FRAME", "CD1I_INVENTORY", "CD0_TRIADIC_DECISION"],
    },
    {
        "family_id": "F2_UEQ0_MASTER",
        "name": "UEQ0 unified-equation master transition",
        "final_class": "ACTIVE_GLOBAL_SOURCE_EXTENSION_CANDIDATE",
        "summary": "Typed state X_t=(nu_t,{Q_mu},{L_mu},G_t,R,d_t); master kernel Pr_t(b,s)=p_t(b)*prod_mu K_led(s_mu|L_mu,m_mu+C_b,mu); proven Markov closure and record monotonicity; only declared external input = chronic schedule m_mu,t; exactly two bridge axioms A12/A13 plus hypergeometric FROZEN_MODEL_RULE; prefix-region set R inherited immutable; no genesis state declared.",
        "members": [["G8_ler_v01_and_misc", "UEQ0 unified equation closure"]],
        "overrides": [],
        "cites": ["UEQ0_MASTER", "UEQ0_AXIOMS"],
    },
    {
        "family_id": "F2M_M0_CORE",
        "name": "M0 multi-model unification exact core (finite event structures)",
        "final_class": "ACTIVE_GLOBAL_SOURCE_EXTENSION_CANDIDATE",
        "summary": "Finite event structures with explicit enabled(config) legality and independence relation; closure algebra; supplies the frozen recurrence/even-relief controller pinned by UEQ0. Generic core over supplied configurations; no genesis state and no occurrence measure.",
        "members": [["G3_deu_unification", "M0 multi-model unification exact core"]],
        "overrides": [],
        "cites": ["UEQ0_AXIOMS"],
    },
    {
        "family_id": "F3_SCHEDULER_LINE",
        "name": "Triangulated scheduler / operational-gravity line (foam, 01-series, rung v7-v30, voids v31 lines, bridge campaigns, holo foam)",
        "final_class": "TRIANGULATED_SCHEDULER_FAMILY",
        "summary": "Live typed face complexes with boundary-counted stochastic schedulers, forced/vacuum token lotteries, backlog/relief valves (v21 Zeno certified base), sector ledgers (v22-v23), conscription (v30), and voids-side flux/shadow/backreaction instrument rounds. Internal opportunity laws ARE defined (scheduler lotteries in source); seeded arbitrary initial substrates; no genesis from primitives; no ancestry retained; no exact state map from or to the registry/OD0 families.",
        "members": [["G1_rmr_logical_seed", "Causal foam event-DAG engine"],
                    ["G1_rmr_logical_seed", "01N topology-stitch pilot"],
                    ["G1_rmr_logical_seed", "01Q coherent topological stitch layer-3 engine"],
                    ["G1_rmr_logical_seed", "01-series fixed-epoch defect/lapse experiment line"],
                    ["G1_rmr_logical_seed", "Rung1 v7"],
                    ["G1_rmr_logical_seed", "Rung1 v8 native-overflow scheduler"],
                    ["G1_rmr_logical_seed", "Rung1 v9"],
                    ["G1_rmr_logical_seed", "Rung1 v19 live valve"],
                    ["G1_rmr_logical_seed", "Rung1 v20 spike"],
                    ["G1_rmr_logical_seed", "Rung1 v21 Zeno"],
                    ["G3_deu_unification", "Rung1 v21 Zeno native-overflow engine"],
                    ["G3_deu_unification", "Rung1 v22 sector-ledger engine"],
                    ["G3_deu_unification", "Rung1 v23 two-window engine"],
                    ["G3_deu_unification", "Rung2 v30 conscription engine"],
                    ["G4_deu_voids", "Distributed flux geometry probe line"],
                    ["G4_deu_voids", "Integer metric-pressure shadow line"],
                    ["G4_deu_voids", "Work-energy carrier C-line"],
                    ["G4_deu_voids", "Track-B xi/spine engine forks"],
                    ["G6_holo_bridge_sr", "F1 DEU_holo HolographicFoamEngine"],
                    ["G6_holo_bridge_sr", "F14 DEU_bridge v21-zeno anchored-patcher calibration campaign"],
                    ["G2_rmr_deu_and_137sim", "DEU activation-count boundary vacuum engine"]],
        "overrides": [["G2_rmr_deu_and_137sim", "DEU activation-count boundary vacuum engine",
                       "ACTIVE_NATIVE_DISTINCTION_CONSTRUCTOR", "TRIANGULATED_SCHEDULER_FAMILY",
                       "Boundary-face activation foam with its own firing rule; state space is a face foam with activation counts, not the recursive unordered-pair universe; merging with F1 would be a name/terminology merge, which Section 6 forbids. Its Lambda carrier-density closure objects are recorded separately under F5."]],
        "cites": ["LEDGER", "CENSUS"],
    },
    {
        "family_id": "F3X_G2C_BACKREACTION",
        "name": "G2c coupled-backreaction line (DEU_voids rounds 22-24: rung2_v31l coupled veto, v31m smoothed coupling)",
        "final_class": "ACTIVE_GLOBAL_SOURCE_EXTENSION_CANDIDATE",
        "summary": "Census addition beyond the descent ledger: executable v31-lineage sources exist in DEU_voids (the ledger recorded v31l-v31o as absent in the linked forces_unification repo; the DEU_voids Fable-line implementations are a distinct later source line with explicit post-legality veto hooks). Initial state = archived mature v30-line substrate; gravity-motivated coupling.",
        "members": [["G4_deu_voids", "G2c coupled-backreaction line"]],
        "overrides": [],
        "cites": ["CENSUS", "PROVENANCE"],
    },
    {
        "family_id": "F4_COLLISION_SUBSTRATE",
        "name": "Collision substrate line (Stage-K toolkit, Open-Token carrier engine, reduced carrier models, collider audits)",
        "final_class": "COLLISION_SUBSTRATE_FAMILY",
        "summary": "Substrate generation, candidate discovery, particle/capsule recognizers, collision control and scoring are separately sourced components (recorded separately per package Section 6 F4); Run3_Dijet named artifacts NOT FOUND on this machine (DEU_LHC3 is an empty placeholder).",
        "members": [["G2_rmr_deu_and_137sim", "Stage-K traceable collision/hadron toolkit"],
                    ["G9_rmr_side_trees", "Open-Token 137-Registry carrier engine"],
                    ["G9_rmr_side_trees", "Alternative-logic multi-force RMR constructors"],
                    ["G4_deu_voids", "Carrier count-face reduced model"],
                    ["G6_holo_bridge_sr", "F7 CMS dijet chi=2 stutter reproduction"]],
        "overrides": [],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "F5_COSMOLOGY_PROJECTION",
        "name": "Cosmology projection line (dynamic-G/S8, graph-clock cosmology, K5 fission CMB, CMB thread-tracing, Boltzmann dual-clock, CLASS-DEU gating, voids E6/A1, Lambda carrier-density closure)",
        "final_class": "COSMOLOGY_PROJECTION_FAMILY",
        "summary": "Each member classified per Section 6 F5: engine-side state fields where an engine exists (K5 fission graph; thread-tracing states), derived observables, external calibrations, and phenomenological projections/locked laws elsewhere. None is a source state map into the active chain.",
        "members": [["G9_rmr_side_trees", "Dynamic-G / S8 growth-screen family"],
                    ["G9_rmr_side_trees", "Graph-clock cosmology candidate line C3B-open4"],
                    ["G9_rmr_side_trees", "K5 fission causal-graph engine"],
                    ["G2_rmr_deu_and_137sim", "DEU CMB thread-tracing / sky-projection harness"],
                    ["G2_rmr_deu_and_137sim", "DEU dual-clock Boltzmann milestone package"],
                    ["G4_deu_voids", "E6/A1 void-boundary generative-age pipeline"]],
        "overrides": [],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FX_HOLO_STAGE",
        "name": "DEU_holo 3D finite-volume field / particle-mesh / Regge stage ladder",
        "final_class": "LEGACY_NONACTIVE",
        "summary": "Deterministic PDE-style stage ladder toward geometric targets; configured (not source-declared) initial data; no availability/opportunity structure; no exact map to any active family.",
        "members": [["G6_holo_bridge_sr", "F2 DEU_holo 3D finite-volume field"]],
        "overrides": [["G6_holo_bridge_sr", "F2 DEU_holo 3D finite-volume field",
                       "ACTIVE_GLOBAL_SOURCE_EXTENSION_CANDIDATE", "LEGACY_NONACTIVE",
                       "No declared genesis, no opportunity structure, and no interface artifacts to OD0 or the constructor; retained in the GM audit as a candidate row but classified nonactive."]],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FX_SR_OBSERVER",
        "name": "DEU_SR self-reference observer family (incompleteness frontier, shared past, objectivity campaigns)",
        "final_class": "AUDIT_ONLY",
        "summary": "Registry-based observer/self-reference audits; initial state = completed 137 registry (archived mature substrate, hostile control 8 scope); the incompleteness frontier is an availability object of the audit, not a global maturation source.",
        "members": [["G6_holo_bridge_sr", "F16 DEU_SR self-reference observer family"],
                    ["G3_deu_unification", "SR0 self-reference frontier exact model"]],
        "overrides": [["G6_holo_bridge_sr", "F16 DEU_SR self-reference observer family",
                       "ACTIVE_GLOBAL_SOURCE_EXTENSION_CANDIDATE", "AUDIT_ONLY",
                       "Starts from the completed registry; no genesis, no OD0 interface; kept as GM candidate row with first-failure GM2."]],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FX_WILLOW",
        "name": "Willow bipartite-lattice signal-propagation engine",
        "final_class": "LEGACY_NONACTIVE",
        "summary": "Fixed bipartite lattice, fixed propagation rule, no genesis, no selection structure, no DEU-chain interface.",
        "members": [["G9_rmr_side_trees", "Willow bipartite-lattice signal-propagation engine"]],
        "overrides": [["G9_rmr_side_trees", "Willow bipartite-lattice signal-propagation engine",
                       "ACTIVE_GLOBAL_SOURCE_EXTENSION_CANDIDATE", "LEGACY_NONACTIVE",
                       "No genesis, no availability semantics, no interface; not an active extension candidate."]],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FX_SPECTRAL_PACKET",
        "name": "Rank-capacity / support-attractor spectral packet dynamics (DEU_holo)",
        "final_class": "AUDIT_ONLY",
        "summary": "Deterministic spectral fixed-point probe; not the OD0 local law.",
        "members": [["G6_holo_bridge_sr", "F4 Rank-capacity / support-attractor spectral packet dynamics"]],
        "overrides": [["G6_holo_bridge_sr", "F4 Rank-capacity / support-attractor spectral packet dynamics",
                       "ACTIVE_OD0_LOCAL_EXACT", "AUDIT_ONLY",
                       "ACTIVE_OD0_LOCAL_EXACT is reserved for the frozen OD0 law family; this is an exploratory holo-side probe with a different state space and no OD0 objects."]],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FX_CONSTRUCTOR_VARIANTS",
        "name": "Scheduler-augmented distinction-constructor variants (HL1 horizon-loss, TX1/TX2/TX3 frontier-scheduled)",
        "final_class": "LEGACY_NONACTIVE",
        "summary": "Distinction-pair constructors with ADDED eligibility/selection policies (combination horizon; frontier scheduling). Their existence is direct source evidence that a selection law over enabled adjunctions is an added policy premise, never derived from the constructor itself (GM4 witness for F1).",
        "members": [["G6_holo_bridge_sr", "F12 HL1 horizon-loss distinction engine"],
                    ["G6_holo_bridge_sr", "F13 TX1 frontier-scheduled distinction engine"]],
        "overrides": [["G6_holo_bridge_sr", "F12 HL1 horizon-loss distinction engine",
                       "ACTIVE_NATIVE_DISTINCTION_CONSTRUCTOR", "LEGACY_NONACTIVE",
                       "Adds a horizon eligibility policy to the constructor; distinct transition; not the frozen native family."],
                      ["G6_holo_bridge_sr", "F13 TX1 frontier-scheduled distinction engine",
                       "ACTIVE_NATIVE_DISTINCTION_CONSTRUCTOR", "LEGACY_NONACTIVE",
                       "Adds a frontier scheduling policy; distinct transition; not the frozen native family."]],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FA_AUDIT_HARNESSES",
        "name": "Standalone audit/reduction harness group (sterile capture, psi0, closure spaces, Zeno scalar, tunneling, SR fingerprint, ringdown lines, LIGO/QM public-data audits, v21 enumerator, TaskP0 provenance, tail-cliff, B0/C26 instruments, crystallization probe, collider audits, unified U0-U3a, CLASS-DEU gating, mass/G-const/LIV/pulsar/blazar audits, RMR applications)",
        "final_class": "AUDIT_ONLY",
        "summary": "Read-only or synthetic-state harnesses; no autonomous global state claims; grouped for the census histogram with members enumerated in the raw census.",
        "members": [["*", "ALL_REMAINING_AUDIT_ONLY"]],
        "overrides": [],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FL_LEGACY",
        "name": "Legacy nonactive engines (HetSim, RMRNode line, RMR lattice engines, cavity census, pre-registry notebooks, legacy copies)",
        "final_class": "LEGACY_NONACTIVE",
        "summary": "Superseded or exploratory engines with no active-chain role; members enumerated in the raw census.",
        "members": [["*", "ALL_REMAINING_LEGACY_NONACTIVE"]],
        "overrides": [],
        "cites": ["CENSUS"],
    },
    {
        "family_id": "FM_MANUSCRIPT",
        "name": "Manuscript-only line (QM_GR papers, GR_QM revision, grav_geometry, v31l-v31o claims (forces_unification repo), HT4 registration, unified_deu_eq drafts, constants map, deu_equations corpus)",
        "final_class": "MANUSCRIPT_ONLY",
        "summary": "Claims with no executable source or with source gaps recorded in MISSING_PROVENANCE.md; the two unified_deu_eq PDFs are hash-pinned with headings-only access.",
        "members": [["*", "ALL_REMAINING_MANUSCRIPT_ONLY"]],
        "overrides": [],
        "cites": ["LEDGER", "PROVENANCE"],
    },
    {
        "family_id": "FQ_QUARANTINED",
        "name": "Quarantined/sealed artifacts (BELL2 packages; Codex-side od0_r48..r53 round outputs)",
        "final_class": "QUARANTINED",
        "summary": "BELL2 scientific content never opened (hash/size pins only). Codex-side R48-R53 outputs excluded from this round's inputs by the v0.2 package; names/sizes/hashes only.",
        "members": [["G7_ler_v2_codex", "od0_r48-r53 Codex-side later rounds"]],
        "overrides": [],
        "cites": ["CENSUS"],
    },
]

# ---------------------------------------------------------------------------
# GM1-GM12 admissibility matrix. Verdicts: PASS / FAIL / SCOPED / NOT_A_CANDIDATE.
# Every FAIL/SCOPED carries its first exact obstruction.
# ---------------------------------------------------------------------------
GM_MATRIX = {
    "F0_OD0_LOCAL": {
        "GM1": ["PASS", "Z carried exactly between updates (R32 cocycle; R33 Sec 1.1-1.2)."],
        "GM2": ["FAIL", "Arbitrary legal prestate law; no genesis state; the three BELL0 preparations are initial injection states, explicitly not proven members of the recurrent event-boundary domain (R33 Sec 1.3)."],
        "GM3": ["PASS", "Exact triangular one-step law with Chapman-Kolmogorov composition (R32)."],
        "GM4": ["FAIL", "Frozen R30: no active source supplies occurrence opportunity, control selection, physical timing, or next-record lifecycle for the OD0 family; the law is explicitly externally controlled (gamma supplied), which disqualifies it as an autonomous maturation source; external-control classification is exact, opportunity remains missing."],
        "GM5": ["PASS", "Triangular updates retain every read field; premise-invariant dependency interval (R43/R44); persistent content support S monotone."],
        "GM6": ["FAIL", "No origin-to-late closure: no origin state; single frozen depth-1 registered domains (Q1/Q2)."],
        "GM7": ["PASS", "Identity map to Z_OD0."],
        "GM8": ["PASS", "Identity restriction commutes trivially."],
        "GM9": ["FAIL", "Controls are supplied, not determined: no source object restricts Gamma_5184 as a function of state; R30/R32 external-control bundle."],
        "GM10": ["PASS", "Source covariance proven (R34 maximal source-correct covariance action; factor exchange R47)."],
        "GM11": ["SCOPED", "Lambda is read by K_svc and N/S grow monotonically, so state fields exist that differ across evolution stages; but no source theorem distinguishes developmental REGIMES (as opposed to values), and no epoch structure is licensed."],
        "GM12": ["PASS", "No target-derived definitions; numerics sealed."],
    },
    "F1_NATIVE_CONSTRUCTOR": {
        "GM1": ["PASS", "Construction state X carried exactly (CD0 report: State(O), successor X union {y})."],
        "GM2": ["PASS", "Exact declared genesis: primitives {a,b} (CD0 spec Sec 1; report)."],
        "GM3": ["PASS", "Adjunction events are a genuine transition/constructor; the trace category is derived, not an enumeration order (CD0 report: successor independent of enumeration/allocation identity)."],
        "GM4": ["FAIL", "First exact obstruction of the round. The constructor defines the enabled-event set (legality) but NO opportunity/selection law: CD0 report 'not a claim about a legacy runtime scheduler'; trace theorem makes construction order physically outcome-free; no source declares which enabled event occurs or whether any occurs. R30 (frozen) independently establishes that no active outer source supplies opportunity on the OD0 side. Direct source evidence that selection is an added premise: the HL1/TX1 variants (FX_CONSTRUCTOR_VARIANTS) implement selection only by adding explicit new policies."],
        "GM5": ["PASS", "States grow monotonically; every field read by future updates (ancestry, parents) is retained; nothing recomputed."],
        "GM6": ["SCOPED", "One state/transition family covers genesis {a,b} through the complete frozen universe O_<=7 (origin-to-complete closure WITHIN the frozen universe). The frozen source universe stops at DAG level 7; no source object defines continuation beyond it, and completeness at level 7 is universe exhaustion, not a proven 'late/mature' physical domain."],
        "GM7": ["FAIL", "No exact map X -> legal OD0 prestate Z: see LG matrix; first failing component is the A12 alphabet (S) which exists only under bridge axiom A12 (UEQ0 axiom ledger: NEW_BRIDGE_AXIOM_A12)."],
        "GM8": ["FAIL", "Not stateable: F1 has no probability law to commute with Pr(h,sigma|Z,gamma); its arrows are unweighted adjunctions."],
        "GM9": ["FAIL", "X determines the enabled adjunction set E(X) exactly (native availability functor), but determines NO subset of the OD0 control domain Gamma_5184 and no proof of full availability exists; no source object connects construction states to query-plus-setting controls."],
        "GM10": ["PASS", "Primitive exchange C2 is a natural automorphism of the event category (CD0 report Symmetry); covariance of frames proven in CD1I."],
        "GM11": ["PASS", "Level-occupancy, ideal size, and enabled-frontier fields are read by the legality relation itself (E(X) is both state-derived and availability-determining), and distinguish structural regimes (growing frontier vs exhausted frontier) without any external counter."],
        "GM12": ["PASS", "CD0 is UEQ-blind by frozen criterion 8 (spec Sec 6); no broadening/onset/cosmology input anywhere."],
    },
    "F2_UEQ0_MASTER": {
        "GM1": ["PASS", "X_t=(nu,{Q_mu},{L_mu},G_t,R,d) carried exactly; proven Markov closure (UEQ0 master theorem)."],
        "GM2": ["FAIL", "No genesis state and no classified initial family: the prefix-region set R is 'immutable inherited'; nu_0 unspecified; initial states are inherited from the frozen LER/BELL0 side."],
        "GM3": ["PASS", "Master kernel with proven normalization and successor law."],
        "GM4": ["SCOPED", "Explicitly classified externally controlled: 'the only declared external input is the next nonnegative integer chronic schedule m_mu,t'. The classification branch of GM4 is satisfied exactly, but the process is thereby not an autonomous maturation source; no source supplies m."],
        "GM5": ["PASS", "Record monotonicity theorem: retained fact graph immutable induced subgraph; ledgers complete; clocks persistent."],
        "GM6": ["FAIL", "No origin: covers arbitrary typed states but no source-declared earliest domain."],
        "GM7": ["FAIL", "Partial: branch/record/clock components correspond to OD0 upstream objects; but the correspondence of L_mu to Lambda and of chronic input to service draws holds only under A12/A13 (NEW_BRIDGE_AXIOMs) and the hypergeometric FROZEN_MODEL_RULE; control sorts differ (m in N_0 per region vs gamma in Gamma_5184) with no source map."],
        "GM8": ["FAIL", "Kernel shapes match (p * prod K factorization) but coefficientwise commutation with the OD0 law is unproven and requires the missing control-sort map (LG6/LG8)."],
        "GM9": ["FAIL", "X_t does not determine legal OD0 controls; the chronic schedule is not a function of state."],
        "GM10": ["PASS", "Source covariance of the kernel under declared symmetries (no hidden selectors; axiom ledger parameter audit)."],
        "GM11": ["PASS", "L_mu and Q_mu are read by the kernel and evolve; ledger/clock fields can in principle distinguish regimes without an external counter."],
        "GM12": ["PASS", "Zero fitted parameters, zero external target curves (axiom ledger)."],
    },
    "F2M_M0_CORE": {
        "GM1": ["PASS", "Configurations carried; closure algebra exact."],
        "GM2": ["FAIL", "Generic core over supplied configurations; no genesis, no classified initial family."],
        "GM3": ["PASS", "Event application is a defined transition."],
        "GM4": ["FAIL", "enabled(config) is legality only; no occurrence measure or selection law."],
        "GM5": ["PASS", "Finite event structures retain event sets."],
        "GM6": ["FAIL", "No origin-to-late coverage."],
        "GM7": ["FAIL", "No map to Z_OD0 components beyond shape analogy."],
        "GM8": ["FAIL", "No probability law."],
        "GM9": ["FAIL", "No control determination."],
        "GM10": ["PASS", "Independence/diamond structure exact."],
        "GM11": ["FAIL", "No developmental field beyond configuration size; no read-relevant regime field identified."],
        "GM12": ["PASS", "No target data."],
    },
    "F3_SCHEDULER_LINE": {
        "GM1": ["PASS", "Foam state carried per epoch (v21 certified base)."],
        "GM2": ["FAIL", "Seeded arbitrary initial substrates; no genesis from primitives; anchored campaigns start from archived substrates (hostile control 8 scoped)."],
        "GM3": ["PASS", "Explicit stochastic transitions (split/flip/collapse/tick with scheduler lottery)."],
        "GM4": ["PASS", "Internal opportunity law defined in source: boundary-counted mixed-token scheduler lottery with capacity veto and backlog (v21)."],
        "GM5": ["FAIL", "Ancestry/history not retained (v21 retains no event ancestry; ledger row); earlier reads not reconstructible."],
        "GM6": ["FAIL", "No origin; epoch index only."],
        "GM7": ["FAIL", "No exact map to Z_OD0: no source object produces the A12 alphabet, Q2 frontier, or P4 histories from foam state; shared words ('stitch','carrier','clock') are not maps (Section 5.3)."],
        "GM8": ["FAIL", "No commuting law: transition sorts differ (face moves vs record-branch events); no intertwiner exists in source."],
        "GM9": ["FAIL", "No OD0 control determination."],
        "GM10": ["SCOPED", "Engine-level symmetries only (face-type invariants); no declared source-covariance action shared with the active chain."],
        "GM11": ["PASS", "Backlog/vacuum-demand fields are read by the scheduler and distinguish load regimes (engine-internal)."],
        "GM12": ["SCOPED", "Later members are gravity/target-motivated (v31 lines); the classification here uses structure only; no numerics were parsed in this round."],
    },
    "F3X_G2C_BACKREACTION": {
        "GM1": ["PASS", "Engine state carried."],
        "GM2": ["FAIL", "Initial state = archived mature v30-line substrate (exactly hostile control 8's pattern; scoped, not repaired)."],
        "GM3": ["PASS", "Coupled veto transitions defined in source."],
        "GM4": ["PASS", "Post-legality opportunity hooks explicit in source."],
        "GM5": ["FAIL", "No ancestry retention (inherits v21-line state schema)."],
        "GM6": ["FAIL", "No origin coverage."],
        "GM7": ["FAIL", "No OD0 map."],
        "GM8": ["FAIL", "No intertwiner."],
        "GM9": ["FAIL", "No OD0 control determination."],
        "GM10": ["SCOPED", "Engine-level only."],
        "GM11": ["PASS", "Metric-work/veto fields read by dynamics."],
        "GM12": ["FAIL", "Gravity-condensation-motivated coupling imported into the transition (hostile control 11 pattern applies to any use of it toward the active chain; recorded as its first GM12-relevant obstruction, no numerics parsed)."],
    },
    "FX_HOLO_STAGE": {
        "GM1": ["PASS", "Field state carried."],
        "GM2": ["FAIL", "Configured initial data; no source-declared genesis."],
        "GM3": ["PASS", "Deterministic staged updates."],
        "GM4": ["FAIL", "No opportunity structure (deterministic PDE-style)."],
        "GM5": ["PASS", "Fields persist."],
        "GM6": ["FAIL", "No origin coverage."],
        "GM7": ["FAIL", "No OD0 objects."],
        "GM8": ["FAIL", "No intertwiner."],
        "GM9": ["FAIL", "No control determination."],
        "GM10": ["SCOPED", "Lattice symmetries only."],
        "GM11": ["FAIL", "No regime-distinguishing read-relevant field identified."],
        "GM12": ["FAIL", "Stage ladder built toward geometric physics targets (structural classification only)."],
    },
    "FX_SR_OBSERVER": {
        "GM1": ["PASS", "Audit state carried."],
        "GM2": ["FAIL", "Starts from the completed 137 registry: archived mature substrate as initial state (hostile control 8 scope)."],
        "GM3": ["PASS", "Forced-growth rule defined."],
        "GM4": ["SCOPED", "The incompleteness frontier defines forced growth (an internal availability object), but selection among forced options is unspecified."],
        "GM5": ["PASS", "Frontier retained."],
        "GM6": ["FAIL", "No origin coverage."],
        "GM7": ["FAIL", "No OD0 map."],
        "GM8": ["FAIL", "No intertwiner."],
        "GM9": ["FAIL", "No control determination."],
        "GM10": ["SCOPED", "Registry symmetries inherited."],
        "GM11": ["PASS", "Frontier set is read-relevant."],
        "GM12": ["PASS", "No target data."],
    },
    "FX_WILLOW": {
        "GM1": ["PASS", "Lattice state carried."],
        "GM2": ["FAIL", "Fixed lattice; no genesis."],
        "GM3": ["PASS", "Fixed propagation rule."],
        "GM4": ["FAIL", "No opportunity/selection structure."],
        "GM5": ["PASS", "State persists."],
        "GM6": ["FAIL", "No origin coverage."],
        "GM7": ["FAIL", "No OD0 objects."],
        "GM8": ["FAIL", "No intertwiner."],
        "GM9": ["FAIL", "No control determination."],
        "GM10": ["SCOPED", "Lattice symmetry only."],
        "GM11": ["FAIL", "No regime field."],
        "GM12": ["PASS", "No target data."],
    },
}

# ---------------------------------------------------------------------------
# LG1-LG12 interface audits for the two substantive candidates (plus the
# scheduler line, which is NO_MAP throughout).
# ---------------------------------------------------------------------------
LG_MATRIX = {
    "F1_NATIVE_CONSTRUCTOR": {
        "LG1": ["FAIL", "The 356-object A12 alphabet is generated by bridge axiom A12 (primitive commitment compiler), classified NEW_BRIDGE_AXIOM_A12 in the UEQ0 axiom ledger and explicitly out of scope of the CD1I descent; therefore no candidate global state determines it from the constructor. D/L/M event-local status is carried by the OD0 rounds, not by X."],
        "LG2": ["PARTIAL", "Exact proved precursor at representation level: CD1I derives the frontier word space, refinement isometry, and A10 prefix-record structure canonically from lineage incidence frames (CANONICAL_DERIVED, certificate list). The specific 36-coordinate Q2 record frontier additionally requires the registered BELL0 depth-1 domain instance (initial injection states), which is registered on the OD0 side and not determined by a construction state."],
        "LG3": ["FAIL", "Exact obstruction: the CD0 trace theorem proves construction order cannot be a physical outcome or retained record (one trace class per comparable state pair). A P4 history or any finite multiset/order of occurrences is therefore not a function of a construction state; F1 retains no history object. This is a theorem-level obstruction, not a missing artifact."],
        "LG4": ["FAIL", "Lambda (regional ledger service prestate, R40 frozen minimal prestate) exists only under A12/A13 bridge axioms plus the hypergeometric FROZEN_MODEL_RULE (UEQ0 axiom ledger); none is constructor-derived; A13 clock-service identity is exactly the layer CD1I lists as out of scope."],
        "LG5": ["FAIL", "(G-,G+) = (Int(R), Cl(R)) over the RRP1 served-request mark set (R43/R44); RRP1 is a declared evidential premise, not source-derived; F1 has no served-mark object."],
        "LG6": ["FAIL", "No determined subset Gamma(X) of Gamma_5184 and no full-availability proof; the constructor's exact availability functor is E(X) (enabled adjunctions), an object of a different sort with no source map to query-plus-setting controls."],
        "LG7": ["FAIL", "Same witness as GM4: no occurrence law; the trace category is silent on whether/where a local event occurs; CD0 explicitly disclaims scheduling."],
        "LG8": ["FAIL", "Not stateable: no probability law on the F1 side."],
        "LG9": ["PARTIAL", "Componentwise: the S-update S' = S union J_h has the same monotone-union shape as adjunction (X' = X union {y}) and the N-update is a unit increment, so a decomposition/order theorem in the sense of GM8 is shape-compatible; but it cannot be completed while LG1 (alphabet) and LG3 (histories) fail."],
        "LG10": ["PASS", "No conflation introduced: CD1I's depth embedding and canonical ternary odometer preserve the direct-limit clock structure (certificate: 'canonical ternary odometer and depth embedding'); local instrument depth D and construction-ideal size are kept distinct sorts throughout this round."],
        "LG11": ["PARTIAL", "Primitive exchange C2 acts covariantly on incidence frames (CD1I); OD0's factor exchange and region/prefix actions are proven source-covariant on the OD0 side (R34/R47); no theorem identifies the two actions across the interface, and none is asserted."],
        "LG12": ["PASS", "No maturity overclaim: completeness of O_<=7 is recorded as universe exhaustion, not origin-to-maturity closure."],
    },
    "F2_UEQ0_MASTER": {
        "LG1": ["CONDITIONAL", "The A12 workload is a component of nu_t by construction, so the alphabet is internal - but only by bridge axiom A12; not source-derived. Classification: determined-by-axiom, not determined-by-source."],
        "LG2": ["PARTIAL", "nu_t contains normalized frontier states of frozen F3R branches; correspondence to the exact 36-coordinate Q2 frontier is by inheritance of the same frozen LER objects, unproven as an exact componentwise map in any source artifact."],
        "LG3": ["PARTIAL", "G_t retains the immutable fact graph and A11R facts (record monotonicity theorem), so retained record histories exist; no source theorem produces the exact 2,304-symbol P4 multiset from G_t; conditional on ERL1/PBO1 on the OD0 side."],
        "LG4": ["CONDITIONAL", "L_mu is a five-integer regional ledger evolving by the hypergeometric kernel; matches Lambda's role only under A12/A13 + FROZEN_MODEL_RULE; the identification is by shared frozen definition, not by a proven intertwiner."],
        "LG5": ["CONDITIONAL", "Service realizations s_mu exist per step; persistent served marks (RRP1) and their interval hull (G-,G+) are OD0-round constructions conditional on RRP1."],
        "LG6": ["FAIL", "Control sorts differ exactly: F2's external input is m_mu,t in N_0 per region; OD0's is gamma in Gamma_5184 (query-plus-setting). No source object maps one to the other; neither is a function of state."],
        "LG7": ["FAIL", "Occurrence is driven by the external chronic schedule; explicitly classified external; no internal opportunity law."],
        "LG8": ["FAIL", "Factorization shapes agree (p * prod K), but coefficientwise commutation is unproven and blocked first by the LG6 control-sort mismatch."],
        "LG9": ["PARTIAL", "Successor structure (retain records, install ledgers, advance clocks, consume served increment) parallels the OD0 triangular updates componentwise; completion blocked by LG4/LG5 conditionality."],
        "LG10": ["PASS", "Depth/covariance metadata d_t kept distinct from any physical time; no conflation."],
        "LG11": ["PARTIAL", "Regional/prefix structure R immutable and covariant; cross-family identification with OD0's region/prefix actions unproven."],
        "LG12": ["PASS", "No maturity overclaim in source."],
    },
    "F3_SCHEDULER_LINE": {
        "LG1": ["FAIL", "No A12 objects; face types S/I/G are not the 356 semantic edit objects (shared labels are not maps, Section 5.3; ledger model-to-model table: absent)."],
        "LG2": ["FAIL", "No record frontier object."],
        "LG3": ["FAIL", "No P4 histories; no ancestry retained."],
        "LG4": ["FAIL", "Backlog/vacuum scalars are not the regional ledger Lambda (different sorts; no map)."],
        "LG5": ["FAIL", "No served-mark set."],
        "LG6": ["FAIL", "No OD0 controls."],
        "LG7": ["FAIL", "Internal lottery is an opportunity law for FOAM moves, not for OD0 occurrences; no interface."],
        "LG8": ["FAIL", "No commuting law."],
        "LG9": ["FAIL", "No successor commutation."],
        "LG10": ["PASS", "Epoch index kept distinct from OD0 depth; no conflation made in this round."],
        "LG11": ["FAIL", "No shared symmetry action."],
        "LG12": ["PASS", "No maturity overclaim adopted here (historical epoch labels remain sealed)."],
    },
}

# ---------------------------------------------------------------------------
# Map classifications (Section 5.3; exactly one class per proposed map).
# ---------------------------------------------------------------------------
MAP_CLASSIFICATIONS = [
    {"map": "F1 construction state/event -> LER representation core (qutrit, F3 transform, frontier words, oriented shift, nested clock, A9 fiber, A10 records, A11R facts) via typed incidence frame (IN=p, CO=q, NEW=x)",
     "class": "EXACT_FUNCTORIAL_RESTRICTION",
     "scope": "Representation-schema level only, on the listed components; certificate: CD1I CANONICAL_FUNCTORIAL_SUBCONSTRUCTION + CANONICAL_DERIVED_REPRESENTATION with zero added axioms. Caveats bound to the certificate: complex linearization/Hilbert substrate inherited from frozen UEQ0; A12/A13 out of scope; no dynamical (probability-law) intertwiner exists because F1 carries no law.",
     "witness": "CD1I_INVENTORY table rows; CD1I_FRAME."},
    {"map": "F1 construction state -> full OD0 prestate Z=(x,N,S,Lambda,G-,G+)",
     "class": "PARTIAL_OBJECT_MAP_MISSING_TRANSITION",
     "scope": "Component partition: x PARTIAL (representation derived; instance registration missing); N FAIL (trace-theorem obstruction); S FAIL (A12 axiom alphabet); Lambda FAIL (A12/A13/model-rule); (G-,G+) FAIL (RRP1).",
     "witness": "LG matrix rows F1/LG1-LG9."},
    {"map": "F2 UEQ0 state -> OD0 prestate Z",
     "class": "EXACT_FORGETFUL_MAP_NO_DYNAMICAL_INTERTWINER",
     "scope": "Record/clock/branch components forget to OD0 upstream objects by shared frozen definition; the dynamical intertwiner fails first at the control-sort mismatch (m vs gamma) and the A12/A13 conditionality.",
     "witness": "LG matrix rows F2/LG6, LG8; UEQ0_AXIOMS."},
    {"map": "Registry node -> foam face type (F1 -> F3)",
     "class": "NO_MAP",
     "scope": "No function/table/import in any source; S/I/G labels shared as words only.",
     "witness": "MODEL_GENEALOGY.md model-to-model maps table row 1; census G1/G3 confirmations."},
    {"map": "psi0 boundary edge count (432 harness) -> OD0/UEQ0 threshold objects",
     "class": "PARTIAL_COUNT_MAP_NOT_SEMANTIC",
     "scope": "Ledger: normalized numerical overlay, ratio-based empirical calibration; no bijection or conservation law; numeric values sealed this round.",
     "witness": "MODEL_GENEALOGY.md maps table (428.333 -> 432 row)."},
    {"map": "two-queue backlog reduction -> registry conflict structure",
     "class": "MODEL_FAMILY_NAME_MATCH_ONLY",
     "scope": "Reduction consumes v21 trace scalars, not overlap-graph conflicts (ledger).",
     "witness": "MODEL_GENEALOGY.md maps table."},
    {"map": "closure path/phase (Paper-2 harnesses) -> causal ancestry / topological clock",
     "class": "NO_MAP",
     "scope": "Synthetic records vs event DAG; supplied float phase vs epoch/type cycle (ledger).",
     "witness": "MODEL_GENEALOGY.md maps table."},
    {"map": "metric-work field -> generative capacity/veto (manuscript v31 claims onto active chain)",
     "class": "SOURCE_CONFLICT",
     "scope": "Manuscript claims name a v30/transport state coupling; the linked-repo sources are absent (MISSING_PROVENANCE 2); the DEU_voids G2c line implements a veto on the v21/v30 lineage but is a separate later source line whose initial state is an archived substrate; identifying the two would join families by name.",
     "witness": "MISSING_PROVENANCE.md items 2, 18; census G3 (absence verified) + G4 (G2c line exists)."},
    {"map": "chronic schedule m (F2) -> OD0 control gamma in Gamma_5184",
     "class": "NO_MAP",
     "scope": "Different control sorts (per-region integers vs query-plus-setting words); no source object relates them.",
     "witness": "UEQ0_MASTER (external input declaration); R32_SPEC (control domain)."},
    {"map": "CD0 enabled-event availability E(X) -> OD0 legal-control availability Gamma(z)",
     "class": "NO_MAP",
     "scope": "Availability functors of different sorts; no source arrow.",
     "witness": "CD0_REPORT (enabledness); R32_SPEC (Gamma_5184)."},
]

# ---------------------------------------------------------------------------
# Genealogy: vertices are family_ids (+ the LER representation core as an
# interface object); arrows are exact source maps only; conditional arrows
# carry their exact premise lists; rejected arrows go to counterexamples.
# ---------------------------------------------------------------------------
GENEALOGY = {
    "vertices": ["F0_OD0_LOCAL", "F1_NATIVE_CONSTRUCTOR", "F1B_CD1I_DESCENT",
                 "F2_UEQ0_MASTER", "F2M_M0_CORE", "F3_SCHEDULER_LINE",
                 "F3X_G2C_BACKREACTION", "F4_COLLISION_SUBSTRATE",
                 "F5_COSMOLOGY_PROJECTION", "FX_HOLO_STAGE", "FX_SR_OBSERVER",
                 "FX_WILLOW", "FX_SPECTRAL_PACKET", "FX_CONSTRUCTOR_VARIANTS",
                 "FA_AUDIT_HARNESSES", "FL_LEGACY", "FM_MANUSCRIPT", "FQ_QUARANTINED",
                 "LER_REPRESENTATION_CORE"],
    "exact_arrows": [
        {"from": "F1_NATIVE_CONSTRUCTOR", "to": "LER_REPRESENTATION_CORE",
         "map": "CD1I incidence-triad representation functor (CDA1)",
         "preserved": "typed incidence frames, orientation double cover, C2 covariance, lineage words, prefix records, Boolean fact algebra, ternary odometer/depth embedding",
         "forgotten": "nothing on listed components; A12/A13/service side not covered",
         "transition_intertwiner": "NONE (F1 carries no law); representation-schema arrow only",
         "initial_state_compatibility": "genesis {a,b} maps to empty-lineage frame base",
         "covariance": "primitive exchange acts covariantly on frames (CD1I)",
         "injectivity_surjectivity": "not claimed in source; not asserted here",
         "certificate": "CD1I_FRAME + CD1I_INVENTORY (CANONICAL_DERIVED, 0 axioms)"},
        {"from": "F3_SCHEDULER_LINE", "to": "F3_SCHEDULER_LINE",
         "map": "intra-line certified inheritance v21 -> v22 -> ... -> v30 (disabled-path certification) and v21 -> v21i/i2/i3 (measurement-only)",
         "preserved": "state schema and legality predicates per certification",
         "forgotten": "nothing (instrument layers pure-read)",
         "transition_intertwiner": "EXACT within the line per disabled-path certificates",
         "initial_state_compatibility": "shared seeded substrates",
         "covariance": "engine-level",
         "injectivity_surjectivity": "identity-on-state embeddings",
         "certificate": "per-version certification blocks read in census G3; ledger v21->v22...v30 row (exact implemented map)"},
    ],
    "conditional_arrows": [
        {"from": "LER_REPRESENTATION_CORE", "to": "F2_UEQ0_MASTER",
         "premises": ["NEW_BRIDGE_AXIOM_A12", "NEW_BRIDGE_AXIOM_A13",
                      "FROZEN_MODEL_RULE (hypergeometric service / even relief)",
                      "external chronic schedule m_mu,t",
                      "Hilbert/complex substrate inherited from frozen UEQ0"],
         "certificate": "UEQ0_AXIOMS equation inventory + UEQ0_MASTER"},
        {"from": "F2_UEQ0_MASTER", "to": "F0_OD0_LOCAL",
         "premises": ["PBO1", "ERL1", "RRP1 (for G+-)", "CCP1_EXACT_SPARSE (for carrier chains only; R47)",
                      "registered Q1/Q2 depth-1 domain instances", "external control domain Gamma_5184"],
         "certificate": "OD0 round chain R19-R47 (pinned); R44 standing evidential conditions; R47 report"},
    ],
    "rejected_arrows": [
        {"from": "F1_NATIVE_CONSTRUCTOR", "to": "F3_SCHEDULER_LINE",
         "reason": "NO_MAP (no registry-node -> face function/table/import in any source)"},
        {"from": "F1_NATIVE_CONSTRUCTOR", "to": "F0_OD0_LOCAL",
         "reason": "no direct exact arrow: factors through LER_REPRESENTATION_CORE on x-side components only; blocked at A12/A13/RRP1 for S/Lambda/G+- and at the trace theorem for N"},
        {"from": "F3_SCHEDULER_LINE", "to": "F0_OD0_LOCAL",
         "reason": "NO_MAP (all LG rows fail; shared ledger-equation shape is not an intertwiner, package Section 6 F3)"},
        {"from": "F4_COLLISION_SUBSTRATE", "to": "F0_OD0_LOCAL",
         "reason": "NO_MAP; no name-based proton -> CCP1 map permitted or found (CCE4)"},
        {"from": "F5_COSMOLOGY_PROJECTION", "to": "any active family",
         "reason": "projection/calibration objects only; no state arrows"},
        {"from": "FM_MANUSCRIPT (v31l-v31o claims)", "to": "F3X_G2C_BACKREACTION",
         "reason": "SOURCE_CONFLICT (see map classification row); families not joined"},
    ],
    "questions": {
        "Q1_single_component_with_genesis_and_od0": "NO as an exact-arrow component on full states; YES only componentwise: the constructor reaches OD0's record/clock/frontier representation core through the exact CD1I arrow, while S/Lambda/(G-,G+) lie behind conditional (axiom-bearing) arrows.",
        "Q2_directed_path_genesis_to_od0_with_exact_intertwiners": "NO. First missing intertwiner: F1 carries no occurrence/probability law (GM4), so no transition intertwiner can exist at the first arrow out of the constructor; independently, the S/Lambda/G+- components require A12/A13/RRP1.",
        "Q3_scheduler_and_collision_in_component": "NO. Both are exact-arrow-isolated from the constructor/OD0 component (NO_MAP witnesses).",
        "Q4_cosmology_projection_status": "External calibrations and phenomenological projections (with engine-internal state fields where engines exist); none is a state map or observable map of the active chain.",
        "Q5_single_family_covering_early_and_late": "NO. F1 covers genesis-to-complete within the frozen universe but has no maturation dynamics; F2/F0 have no origin; F3 has dynamics but no origin and no interface.",
        "Q6_any_family_passes_GM1_12": "NO. Nearest candidate F1 fails first at GM4.",
    },
}

# ---------------------------------------------------------------------------
# Maturation-field inventory (Section 8).
# ---------------------------------------------------------------------------
MATURATION_FIELDS = [
    # F1 fields
    {"field": "F1 ideal size |X|", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "Exact cardinality; monotone under adjunction; read-relevant via E(X)."},
    {"field": "F1 level-occupancy vector (|X inter O_k|, k=1..7)", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "Exact; distinguishes structural growth regimes; no external counter."},
    {"field": "F1 enabled-event set E(X) and |E(X)|", "class": "ACTIVE_GLOBAL_STATE_FIELD", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "The native availability relation itself; empty exactly at the complete state (frontier exhaustion within the frozen universe)."},
    {"field": "F1 ancestry-poset invariants (height, width, antichain counts)", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "Exact integer/poset invariants."},
    {"field": "F1 C2 primitive-exchange orbit data on X", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "Exact orbit counts; covariant by CD0 symmetry theorem."},
    {"field": "F1 overlap-graph induced subgraph on X inter O_7 (source predicate)", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "Source-backed graph (CD0 Sec 4.2); flag completion is a representation decision, excluded."},
    # F2 fields
    {"field": "F2 regional ledger states L_mu (five integers per region)", "class": "ACTIVE_GLOBAL_STATE_FIELD", "family": "F2_UEQ0_MASTER",
     "notes": "Read by the kernel; exists under A12/A13 axioms (conditionality recorded)."},
    {"field": "F2 character-clock residues/depth/orientation Q_mu", "class": "ACTIVE_GLOBAL_STATE_FIELD", "family": "F2_UEQ0_MASTER",
     "notes": "Persistent; advanced by service counts (A13)."},
    {"field": "F2 retained fact graph G_t (size, region decomposition)", "class": "ACTIVE_GLOBAL_STATE_FIELD", "family": "F2_UEQ0_MASTER",
     "notes": "Immutable growth; record monotonicity theorem."},
    {"field": "F2 branch-measure support of nu_t", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F2_UEQ0_MASTER",
     "notes": "Exact support of the finite normalized measure."},
    # OD0 fields
    {"field": "x (36-coordinate Q2 record frontier)", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL", "notes": "R33 Sec 1.1."},
    {"field": "N (2,304 P4 occurrence multiplicities); Q(N)=sum_h N_h", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL", "notes": "R33."},
    {"field": "S (support in 356-element persistent content alphabet)", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL", "notes": "R33; alphabet under A12."},
    {"field": "Lambda (regional service ledgers), lapse/relief/vacuum distributions", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL", "notes": "R40/R21 typed service; A13R clock."},
    {"field": "(G-,G+) dependency-realization intervals; served marks R", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL", "notes": "R43/R44 under RRP1."},
    {"field": "CCP1 chain count #{e: n_e>0} and max chain length", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL",
     "notes": "Conditional on CCP1_EXACT_SPARSE (not source-derived; R47); function of N."},
    {"field": "direct-limit clock increments; identity-free clock classes", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL", "notes": "R39/R43."},
    {"field": "registered regional status signatures (40)", "class": "LOCAL_OD0_FIELD_ONLY", "family": "F0_OD0_LOCAL", "notes": "R47 execution scope line."},
    # External / engine / historical
    {"field": "gamma control words; policy weights; EOP1 simplex coordinates", "class": "EXTERNAL_CONTROL_METADATA", "family": "F0_OD0_LOCAL",
     "notes": "Supplied, never selected (R32/R35)."},
    {"field": "chronic schedule m_mu,t", "class": "EXTERNAL_CONTROL_METADATA", "family": "F2_UEQ0_MASTER", "notes": "Declared external input."},
    {"field": "engine epoch/sweep counters (v-line, foam, HetSim, harnesses)", "class": "ENGINE_INDEX_ONLY", "family": "F3_SCHEDULER_LINE",
     "notes": "Bare counters; GM11 bar applies."},
    {"field": "v-line backlog, vacuum demand, Gamma valve, sV, tag populations", "class": "UNAVAILABLE", "family": "F3_SCHEDULER_LINE",
     "notes": "Genuine engine state fields, but unavailable as maturation fields for the active source: their family has no exact arrow into the constructor/OD0 component (convention recorded in report Sec 8)."},
    {"field": "global object/edge counts and DAG-size distribution of candidate global states", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "Audit-list item; realized exactly by the F1 fields above."},
    {"field": "generation/layer counts; path counts (audit-list items)", "class": "ACTIVE_GLOBAL_DERIVED_OBSERVABLE", "family": "F1_NATIVE_CONSTRUCTOR",
     "notes": "Exact on P(X) (chain/path counting); no engine-step identification (hostile 3)."},
    {"field": "registry motif exposure / containment / co-embedding support, birth/death, stability, concentration moments", "class": "HISTORICAL_RESULT_ONLY", "family": "FM_MANUSCRIPT",
     "notes": "Defined in the historical distinction-engine analysis (H1); the underlying overlap graph is a source object, but these specific derived motif statistics exist in this corpus only as historical results/paper analyses; values sealed."},
    {"field": "broadening / freeze-out / support-locking / late-concentration labels", "class": "HISTORICAL_RESULT_ONLY", "family": "FM_MANUSCRIPT",
     "notes": "Sealed epoch labels (H1); never assumed exhaustive or ordered (Section 5.5)."},
    {"field": "collision onset counts, mature anchor, availability growth (H2 arc)", "class": "HISTORICAL_RESULT_ONLY", "family": "F4_COLLISION_SUBSTRATE", "notes": "Sealed."},
    {"field": "gravity-strength proxies (dynamic-G locked law, open-to-mature factor)", "class": "MANUSCRIPT_INTERPRETATION", "family": "F5_COSMOLOGY_PROJECTION",
     "notes": "Locked phenomenological law; external calibration; no source state field; values sealed."},
    {"field": "graph-clock / Hubble / S8 projections; containment/coembedding clocks", "class": "MANUSCRIPT_INTERPRETATION", "family": "F5_COSMOLOGY_PROJECTION",
     "notes": "Projection formulas over engine outputs or data; sealed (H3/H4)."},
    {"field": "rho_C carrier density; de Sitter closure; 124/120 factor", "class": "MANUSCRIPT_INTERPRETATION", "family": "F5_COSMOLOGY_PROJECTION", "notes": "Sealed (H5)."},
    {"field": "particle/capsule recognizers and channel availability classifications (Stage-K, Open-Token)", "class": "UNAVAILABLE", "family": "F4_COLLISION_SUBSTRATE",
     "notes": "Source-defined recognizers exist as code within F4, but F4 has no exact arrow into the active component; unavailable as active-source maturation fields."},
]

EPOCH_CANDIDATE_FREEZE = {
    "status": "NO_CANDIDATE_FAMILY_FROZEN",
    "reason": "Section 8 licenses candidate maturation observables only if some family passes GM1-GM10; no family does (nearest: F1, first failure GM4). The F1 field family (level occupancy, |X|, E(X), poset invariants, C2 orbits) is inventoried above as the natural generic-construction pool but is NOT frozen as an epoch-candidate family and no threshold, partition, or basin is proposed.",
    "historical_target_access_used": False,
}

# ---------------------------------------------------------------------------
# CCE audit (Section 9).
# ---------------------------------------------------------------------------
CCE = {
    "CCE1": ["PASS", "No global path licenses any first-appearance tau_e (no family passes GM1-12); tau_e therefore has no value anywhere in this round; occurrence stages remain T_occ order only (R47: physical elapsed time NOT_DEFINED)."],
    "CCE2": ["PASS", "Absent-rank scope re-asserted from the frozen R47 result: absent rank creates no carrier stage; C- subset C_R subset C+; completion charge 0; null completion remains unselected. Asserted from the pinned report; not recomputed."],
    "CCE3": ["FAIL_NO_GLOBAL_FUNCTION", "The set of labels with nonempty chains is #{e: n_e>0}, a function of the LOCAL state component N; no candidate global source determines it (LG3 failures); it is not a state-derived function of any global family."],
    "CCE4": ["PASS", "Carrier labels remain the 356 exact semantic A12 objects; no particle promotion made; F4 recognizers kept in their own family with NO_MAP."],
    "CCE5": ["PASS", "No maturity definition from CCP1; carrier-support fields reported in the inventory (supp(N)-derived, LOCAL_OD0_FIELD_ONLY); no threshold selected."],
}

# ---------------------------------------------------------------------------
# Hostile controls (Section 12): 12 items.
# ---------------------------------------------------------------------------
HOSTILE_CONTROLS = [
    ["HC1", "local depth D equals cosmic epoch", "REJECTED",
     "D indexes the frozen instrument tower (3^D frontier dimension, modulus 3^(D+1)); no source theorem relates it to any global age; the never-identify list is enforced verbatim; no identification appears in any output."],
    ["HC2", "occurrence rank / control-word position equals physical elapsed time or global age", "REJECTED",
     "R47 (frozen): PHYSICAL ELAPSED TIME STATUS: NOT_DEFINED; T_occ IS ORDER ONLY. Reasserted; nothing in this round assigns durations."],
    ["HC3", "object DAG size equals engine step", "REJECTED",
     "Exact witness: at the complete size-six state all 137 size-seven objects are simultaneously enabled (CD0 report), so DAG size and event count are different sorts; the trace theorem removes order entirely."],
    ["HC4", "frontier stationarity equals global support locking", "REJECTED",
     "E(X) = empty at the complete state is exhaustion of the frozen universe O_<=7; the historical 'support locking' label is a sealed H1 result never opened; no identification made."],
    ["HC5", "CCP1 chain existence equals particle existence; one repeated label defines maturity", "REJECTED",
     "CCE4/CCE5; R47: carrier labels stay exact semantic objects; no threshold selected."],
    ["HC6", "null-completing CCP1 through absent ranks", "REJECTED",
     "R47 frozen interval status: ABSENT = NO STAGE, completion charge 0; nothing in this round completes through absence."],
    ["HC7", "threshold or statistic selected using 2.5e5 / 5e5 / proton presence / broadening labels / K9 concentration", "REJECTED",
     "All historical numerical content sealed (numerical_content_parsed=false in all 9 census groups); no threshold or statistic of any kind was selected in this round."],
    ["HC8", "treating a mature archived substrate as the global initial state", "SCOPED_EXACTLY",
     "Present in sources and scoped, not adopted: F3X_G2C and the DEU_bridge anchored campaigns initialize from archived substrates; FX_SR_OBSERVER starts from the completed registry; F2's prefix set R is inherited. Each is recorded as a GM2 failure of its family; none is promoted to a genesis."],
    ["HC9", "treating a test-harness loop or enumeration order as opportunity or dynamics", "REJECTED",
     "CD0's exhaustive level sweep classified as enumeration (successor independent of enumeration); OD0 audit engines classified AUDIT_ONLY; census agents' exhaustive-realization notes never entered GM4 as opportunity."],
    ["HC10", "joining model families by shared names or shared counts (137, 27, 432, 81)", "REJECTED",
     "Merges made only on identical constructor rule + identical universe (F1 merge certificate); the boundary-vacuum foam proposed as constructor was reclassified (override recorded); 432-harnesses kept separate (PARTIAL_COUNT_MAP_NOT_SEMANTIC)."],
    ["HC11", "importing triangulated geometry, a gravity-condensation schedule, or a graph-clock/Hubble formula into state or transition", "REJECTED",
     "F3/F5 objects carry no arrows into the active component; F3X_G2C's gravity-motivated coupling is recorded as that family's own GM12 obstruction, not imported."],
    ["HC12", "digests as physical identities; post-witness candidate repair; modification of R47/inherited roots; opening BELL2", "REJECTED",
     "Hashes used only as pins; no candidate repaired after a witness; frozen-root modification check clean at start and end; BELL2_scientific_content_opened=false throughout (sealed-item lists in census)."],
]

# ---------------------------------------------------------------------------
# Verdicts (Section 14) and smallest gaps (Section 15).
# ---------------------------------------------------------------------------
VERDICTS = {
    "always": "OD0_R48_PASS_EXACT_MODEL_FAMILY_GENEALOGY_AND_MATURATION_SOURCE_BOUNDARY",
    "primary": "HYBRID_B_C",
    "primary_lines": [
        "OD0_R48_PARTIAL_GLOBAL_ENGINE_EXISTS_NO_EXACT_OD0_LOCAL_INTERTWINER",
        "OD0_R48_PARTIAL_OD0_LOCAL_CONTROLLED_COCYCLE_NO_GLOBAL_MATURATION_SOURCE",
    ],
    "primary_justification": "B side: F1 is a genuine origin-to-state constructor (GM1-3,5,10-12 pass; GM6 scoped to the frozen universe) with an exact representation arrow into the OD0 upstream factor (CD1I), but no opportunity law (GM4) and no transition intertwiner; F2 is a proven Markov master engine without genesis and with external chronic input. C side: the OD0 family itself is an exact externally controlled cocycle with no global maturation source (frozen R30). Component partition of Z: x PARTIAL(representation-derived), N FAIL(trace-theorem), S FAIL(A12), Lambda FAIL(A12/A13/model-rule), (G-,G+) FAIL(RRP1).",
    "holdout": "OD0_R48_PARTIAL_HISTORICAL_HOLDOUT_ARTIFACTS_INCOMPLETE",
    "holdout_missing": [
        "H2: no artifact named Run3_Dijet exists under any census root (DEU_LHC3 is an empty placeholder: single 0-byte proposal.txt); the 2.5e5/5e5/8e6 collision-age arc is represented only by Stage-K/Open-Token/CMS-audit artifacts and manuscript PDFs (cern.pdf, carriers.pdf)",
        "H1: distinction_engine_paper_notes.md not found under any census root; the registry paper itself is present only as manuscript-corpus PDFs",
        "H3: v31l-v31o generating sources for grav_geometry Fig.1/Table 1 remain absent (MISSING_PROVENANCE 12); grav_geometry.pdf pinned",
        "H5: no artifact carrying the finite-count de Sitter closure computation located beyond manuscript PDFs (DE_foam pinned)",
    ],
    "smallest_gaps": {
        "global_source": "One missing law: an occurrence/selection structure on the constructor's enabled-event sets E(X) (GM4). Everything else on the B side (genesis, state, transition, persistence, covariance, epoch-relevant fields) already passes for F1.",
        "local_global_interface": "The A12 bridge: the 356-element persistent content alphabet (S's alphabet, LG1) is the first Z-component blocked by a non-source-derived premise; N is blocked one level deeper by the exact trace theorem (order/multiplicity not a function of construction state).",
        "opportunity_availability": "F1's availability functor E(X) is exact and native, but no source object maps it to Gamma_5184 (LG6) and no source supplies an opportunity law over it (LG7/R30).",
    },
    "r49_recommendation": "Per Section 16 (B/C hybrid): address only the smallest exact interface obstruction - ask whether the constructor plus the already-frozen service/RRP1 premises jointly determine Lambda and (G-,G+), BEFORE any new premise. Sharpened by this round's witnesses: the first sub-question is whether the A12 compiler map (canonical F3R primitive -> one forced request in its smallest inherited prefix region) is derivable from the CD1I-descended record algebra (A10/A11R) - A12 is the first non-derived layer between the exact representation core and the entire service side, and Lambda/(G-,G+) both sit behind it.",
}

# Terminal-return skeleton values that the pipeline completes with counts.
TERMINAL_STATIC = {
    "R47_PIN_VERIFICATION": "PASS (manifest sha256 + result digest exact; execution commit not locally resolvable - recorded; chain R47->R30 17/17 links VERIFIED)",
    "BELL2_OPENED": "false",
    "CONTROL_AVAILABILITY_LG6": "F1: native E(X) exact, no map to Gamma_5184; F2: control-sort mismatch (m vs gamma); no full-availability proof anywhere",
    "OPPORTUNITY_LG7": "ABSENT on all candidates (F1: no selection law; F2: external chronic schedule; F0: frozen R30); F3-internal lotteries are engine-scoped only",
    "CCP1_EPOCH_SCOPE": "CCE1/2/4/5 PASS, CCE3 NO_GLOBAL_FUNCTION (N-local)",
    "OD0_RESTRICTION_STATUS": "x: PARTIAL(representation-derived via CD1I; instance registration missing) | N: FAIL(trace-theorem obstruction) | S: FAIL(A12 axiom alphabet) | Lambda: FAIL(A12/A13/model-rule) | G+-: FAIL(RRP1)",
}
